{
 "title": "My Node Exporter Dashboard (Mac)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Available Memory Percentage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free bytes in filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 10 },
   "targets": [
    { "expr": "node_filesystem_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "node_disk_read_time_seconds_total / node_disk_reads_completed_total ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}